name: Build and check
on: [pull_request, push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build the app
        run: ./gradlew build

  android_tests:
    # see https://github.com/reactivecircus/android-emulator-runner,
    # needs to run on macos as only there virtualization is available!
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Instrumentation Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 26
          arch: arm64-v8a
          script: ./gradlew connectedCheck
